name: New Catalog Entry
description: Add a row to the DDF Catalog
title: "[New Catalog Entry] : "
body:
  - type: input
    id: org_name
    attributes:
      label: Organization Name
      description: What is the name of your organization or team?
      placeholder:
    validations:
      required: true
  
  - type: input
    id: product_name
    attributes:
      label: Product Name
      description: What is the name of your Digital Data Flow (DDF) compatible solution or platform?
      placeholder:
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: Primary Point of Contact Email
      description: What is the primary contact email for your product/solution?
      placeholder:
    validations:
      required: true

  - type: input
    id: contact_phone
    attributes:
      label: Primary Point of Contact Phone
      description: What is the primary contact email for your product/solution?
      placeholder:
    validations:
      required: true
  
  - type: textarea
    id: product_maturity
    attributes:
      label: Product Description/Maturity
      description: Please describe your solution, making sure to include how it utilizes the Unified Study Definition Model (USDM), how it enables protocol digitization, and where it sits on teh development lifecycle.
      placeholder:
    validations:
      required: true

  - type: checkboxes
    id: use_cases
    attributes:
      label: Covered Use Cases
      description: Please select one or more of the following use cases which your solution enables.
      options:
        - label: Decentralized Clinical Trials (DCT)
        - label: Diverse and Inclusive Trial Design
        - label: Electronic Data Capture (EDC)
        - label: Electronic Health Record (EHR)
        - label: eSource
        - label: Inclusion / Exclusion criteria
        - label: Operational systems (i.e. CTMS, IRT, etc.)
        - label: Registry reporting
        - label: Regulatory submission
        - label: Other (https://github.com/orgs/community/discussions/15807)
    validations:
      required: true

  - type: dropdown
    id: usdm_version
    attributes:
      label: USDM Version Compatibility
      description: What version of the USDM is your solution compatible with?
      multiple: false
      options:
        - 1.0
        - 1.5
        - 2.0
        - 2.5
        - 2.6
        - 3.0
      default: 0
    validations:
      required: true