name: Update Catalog Run

on:
  issues:
    types: [opened]

env:
  PYTHON_DIR: python
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  update-catalog:
    name: Update Catalog
    runs-on: ubuntu-latest
    steps:
    - name: Check-out python repository
      uses: actions/checkout@v2
      with:
        repository: colin-bradshaw-pac/ddf-home-testing
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.PYTHON_DIR }}

    - name: Run add_row
      run: python ${{ env.PYTHON_DIR }}/add_row.py '${{ env.GITHUB_CONTEXT }}'
      shell: sh

