name: Update Catalog Run

on:
  issues:
    types: [opened]

env:
  PYTHON_DIR: catalog
  GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
  update-catalog:
    name: Update Catalog
    runs-on: ubuntu-latest
    steps:
    - name: Check-out python repository
      uses: actions/checkout@v4
      with:
        repository: colin-bradshaw-pac/ddf-home-testing
        token: ${{ secrets.GITHUB_TOKEN }}
        path: ${{ env.PYTHON_DIR }}

    - name: Check file existence
      id: check_files
      uses: thebinaryfelix/check-file-existence-action@v1
      with:
        files: 'add_row.py'

    - name: Run add_row
      run: python /home/runner/work/ddf-home-testing/catalog/add_row.py '${{ env.GITHUB_CONTEXT }}'
      shell: sh

    - name: commit and push changes
      run: |
        git add --all
        git commit -m "generated"
        git push

